/* The following code was generated by JFlex 1.5.0-SNAPSHOT */


/* --------------------------Codigo de Usuario----------------------- */

package ejemplocup;

import java_cup.runtime.*;
import java.io.Reader;

import static compilador.Tokens.*;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.5.0-SNAPSHOT
 * from the specification file <tt>alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\10\1\2\1\12\1\3\1\1\22\0\1\10\1\24\1\62"+
    "\1\0\1\0\1\23\1\25\1\63\1\17\1\20\1\16\1\14\1\36"+
    "\1\15\1\21\1\11\1\4\11\5\1\35\1\13\1\34\1\22\1\33"+
    "\1\37\1\0\32\6\1\31\1\0\1\32\1\0\1\7\1\0\1\42"+
    "\1\55\1\40\1\57\1\47\1\50\1\6\1\54\1\51\2\6\1\41"+
    "\1\6\1\52\1\56\1\53\1\6\1\45\1\43\1\44\1\46\1\60"+
    "\2\6\1\61\1\6\1\27\1\26\1\30\1\0\6\0\1\12\73\0"+
    "\1\0\7\0\1\0\3\0\1\0\3\0\1\6\1\0\1\0\6\0"+
    "\1\0\6\0\1\0\7\0\1\0\3\0\1\0\3\0\1\6\1\0"+
    "\1\0\6\0\1\0\1\0\1\0\u1f2b\0\1\12\1\12\udfd6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\2\1\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\15\4\2\1\2\0\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\16\4\1\51\7\4"+
    "\1\0\1\52\1\0\1\53\1\4\1\54\1\55\2\4"+
    "\1\56\1\57\2\4\1\60\1\4\1\61\4\4\1\62"+
    "\1\63\3\4\1\64\2\4\1\65\1\66\1\67\1\70"+
    "\1\71\1\72\1\73\1\74\1\75\1\76\1\77\1\100"+
    "\1\101\1\102\1\103";

  private static int [] zzUnpackAction() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\64\0\234\0\320\0\u0104\0\u0138"+
    "\0\64\0\64\0\u016c\0\u01a0\0\u01d4\0\64\0\64\0\u0208"+
    "\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c\0\64\0\64\0\64"+
    "\0\64\0\u0340\0\u0374\0\64\0\64\0\64\0\u03a8\0\u03dc"+
    "\0\u0410\0\u0444\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c"+
    "\0\u05b0\0\u05e4\0\u0618\0\u064c\0\u0680\0\234\0\u0208\0\u06b4"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\u0208\0\64"+
    "\0\64\0\64\0\64\0\64\0\64\0\64\0\u06e8\0\u071c"+
    "\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854\0\u0888\0\u08bc"+
    "\0\u08f0\0\u0924\0\u0958\0\u098c\0\u0104\0\u09c0\0\u09f4\0\u0a28"+
    "\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u064c\0\64\0\u0680\0\64"+
    "\0\u0b2c\0\u0104\0\u0104\0\u0b60\0\u0b94\0\u0104\0\u0104\0\u0bc8"+
    "\0\u0bfc\0\u0104\0\u0c30\0\u0104\0\u0c64\0\u0c98\0\u0ccc\0\u0d00"+
    "\0\u0104\0\u0104\0\u0d34\0\u0d68\0\u0d9c\0\u0104\0\u0dd0\0\u0e04"+
    "\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104"+
    "\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104\0\u0104";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\2\1\4"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\7\1\45\1\46"+
    "\1\47\1\50\1\51\1\7\1\52\1\7\1\53\2\7"+
    "\1\54\1\55\66\0\1\4\65\0\2\56\13\0\1\57"+
    "\46\0\2\6\13\0\1\57\46\0\4\7\30\0\22\7"+
    "\13\0\1\60\10\0\1\61\55\0\1\62\5\0\1\63"+
    "\56\0\1\64\4\0\1\65\63\0\1\66\45\0\2\67"+
    "\100\0\1\70\63\0\1\71\63\0\1\72\66\0\1\73"+
    "\64\0\1\74\57\0\1\75\63\0\1\76\45\0\4\7"+
    "\30\0\1\7\1\77\12\7\1\100\5\7\6\0\4\7"+
    "\30\0\16\7\1\101\3\7\6\0\4\7\30\0\15\7"+
    "\1\102\4\7\6\0\4\7\30\0\4\7\1\103\1\7"+
    "\1\104\12\7\1\105\6\0\4\7\30\0\5\7\1\106"+
    "\6\7\1\107\5\7\6\0\4\7\30\0\7\7\1\110"+
    "\12\7\6\0\4\7\30\0\1\7\1\111\20\7\6\0"+
    "\4\7\30\0\1\7\1\112\1\113\6\7\1\114\10\7"+
    "\6\0\4\7\30\0\10\7\1\115\1\7\1\116\7\7"+
    "\6\0\4\7\30\0\2\7\1\117\3\7\1\120\13\7"+
    "\6\0\4\7\30\0\5\7\1\121\1\122\13\7\6\0"+
    "\4\7\30\0\16\7\1\123\3\7\6\0\4\7\30\0"+
    "\16\7\1\124\3\7\2\0\62\125\1\126\1\125\63\127"+
    "\1\130\1\60\3\0\6\60\1\0\51\60\4\0\4\7"+
    "\30\0\2\7\1\131\17\7\6\0\4\7\30\0\5\7"+
    "\1\132\14\7\6\0\4\7\30\0\12\7\1\133\7\7"+
    "\6\0\4\7\30\0\3\7\1\134\16\7\6\0\4\7"+
    "\30\0\2\7\1\135\17\7\6\0\4\7\30\0\13\7"+
    "\1\136\6\7\6\0\4\7\30\0\12\7\1\137\7\7"+
    "\6\0\4\7\30\0\6\7\1\140\3\7\1\141\7\7"+
    "\6\0\4\7\30\0\5\7\1\142\3\7\1\143\10\7"+
    "\6\0\4\7\30\0\4\7\1\144\15\7\6\0\4\7"+
    "\30\0\3\7\1\145\16\7\6\0\4\7\30\0\16\7"+
    "\1\146\3\7\6\0\4\7\30\0\1\7\1\147\20\7"+
    "\6\0\4\7\30\0\12\7\1\150\7\7\6\0\4\7"+
    "\30\0\4\7\1\151\15\7\6\0\4\7\30\0\4\7"+
    "\1\152\15\7\6\0\4\7\30\0\1\7\1\153\20\7"+
    "\6\0\4\7\30\0\11\7\1\154\4\7\1\155\3\7"+
    "\6\0\4\7\30\0\15\7\1\156\4\7\6\0\4\7"+
    "\30\0\16\7\1\157\3\7\6\0\4\7\30\0\6\7"+
    "\1\160\13\7\6\0\4\7\30\0\3\7\1\161\16\7"+
    "\6\0\4\7\30\0\4\7\1\162\15\7\6\0\4\7"+
    "\30\0\4\7\1\163\15\7\6\0\4\7\30\0\7\7"+
    "\1\164\12\7\6\0\4\7\30\0\3\7\1\165\16\7"+
    "\6\0\4\7\30\0\3\7\1\166\16\7\6\0\4\7"+
    "\30\0\7\7\1\167\12\7\6\0\4\7\30\0\4\7"+
    "\1\170\15\7\6\0\4\7\30\0\3\7\1\171\16\7"+
    "\6\0\4\7\30\0\1\7\1\172\20\7\6\0\4\7"+
    "\30\0\1\7\1\173\20\7\6\0\4\7\30\0\20\7"+
    "\1\174\1\7\6\0\4\7\30\0\4\7\1\175\15\7"+
    "\6\0\4\7\30\0\1\7\1\176\20\7\6\0\4\7"+
    "\30\0\15\7\1\177\4\7\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3640];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\4\1\2\11\3\1\2\11"+
    "\6\1\4\11\2\1\3\11\17\1\2\0\1\1\6\11"+
    "\1\1\7\11\26\1\1\0\1\11\1\0\1\11\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[127];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */

    public String lexeme;
    public int line;
    public int column;

    /*  Generamos un java_cup.Symbol para guardar el tipo de token encontrado */

    private Symbol symbol(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    
    /* Generamos un Symbol para el tipo de token encontrado junto con su valor */

    private Symbol symbol(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  AnalizadorLexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader
             (in, java.nio.charset.Charset.forName("UTF-8")));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 198) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

    // numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { line=yyline;column=yycolumn; lexeme=yytext return symbol(sym.ERROR);
          }
        case 68: break;
        case 2: 
          { /* ignora el espacio */
          }
        case 69: break;
        case 3: 
          { System.out.print(yytext()); line=yyline; column=yycolumn; lexeme=yytext(); return symbol(sym.ENTERO, new Integer(yytext()));
          }
        case 70: break;
        case 4: 
          { System.out.print(yytext()); line=yyline; column=yycolumn; lexeme=yytext(); return symbol(sym.ID, new String(yytext()));
          }
        case 71: break;
        case 5: 
          { System.out.print(" / "); line=yyline; column=yycolumn; return symbol(sym.OP_DIV);
          }
        case 72: break;
        case 6: 
          { System.out.print("Caracter ilegal <"+yytext()+">"); return symbol(sym.ERROR);
          }
        case 73: break;
        case 7: 
          { return symbol(sym.SEMI);
          }
        case 74: break;
        case 8: 
          { System.out.print(" + "); return symbol(sym.OP_SUMA);
          }
        case 75: break;
        case 9: 
          { System.out.print(" - "); return symbol(sym.OP_RESTA);
          }
        case 76: break;
        case 10: 
          { System.out.print(" * "); return symbol(sym.OP_MULT);
          }
        case 77: break;
        case 11: 
          { System.out.print(" ( "); return symbol(sym.PARENIZQ);
          }
        case 78: break;
        case 12: 
          { System.out.print(" ) "); return symbol(sym.PARENDER);
          }
        case 79: break;
        case 13: 
          { System.out.print(" / "); line=yyline; column=yycolumn; return symbol(sym.POINT);
          }
        case 80: break;
        case 14: 
          { System.out.print(" = "); line=yyline; column=yycolumn; return symbol(sym.ASIG);
          }
        case 81: break;
        case 15: 
          { System.out.print(" % "); line=yyline; column=yycolumn; return symbol(sym.MOD);
          }
        case 82: break;
        case 16: 
          { System.out.print(" ! "); line=yyline; column=yycolumn; return symbol(sym.NOT);
          }
        case 83: break;
        case 17: 
          { System.out.print(" { "); line=yyline; column=yycolumn; return symbol(sym.KEYIZQ);
          }
        case 84: break;
        case 18: 
          { System.out.print(" } "); line=yyline; column=yycolumn; return symbol(sym.KEYDER);
          }
        case 85: break;
        case 19: 
          { System.out.print(" [ "); line=yyline; column=yycolumn; return symbol(sym.CORIZQ);
          }
        case 86: break;
        case 20: 
          { System.out.print(" ] "); line=yyline; column=yycolumn; return symbol(sym.CORDER);
          }
        case 87: break;
        case 21: 
          { System.out.print(" < "); line=yyline; column=yycolumn; return symbol(sym.MAYOR);
          }
        case 88: break;
        case 22: 
          { System.out.print(" > "); line=yyline; column=yycolumn; return symbol(sym.MENOR);
          }
        case 89: break;
        case 23: 
          { System.out.print(" : "); line=yyline; column=yycolumn; return symbol(sym.POINTS);
          }
        case 90: break;
        case 24: 
          { System.out.print(" , "); line=yyline; column=yycolumn; return symbol(sym.COMA);
          }
        case 91: break;
        case 25: 
          { System.out.print(" ? "); line=yyline; column=yycolumn; return symbol(sym.INTROG);
          }
        case 92: break;
        case 26: 
          { /*Ignore*/
          }
        case 93: break;
        case 27: 
          { System.out.print(" /= "); line=yyline; column=yycolumn; return symbol(sym.DIVEQ);
          }
        case 94: break;
        case 28: 
          { System.out.print(" ++ "); line=yyline; column=yycolumn; return symbol(sym.INC);
          }
        case 95: break;
        case 29: 
          { System.out.print(" += "); line=yyline; column=yycolumn; return symbol(sym.SUMEQ);
          }
        case 96: break;
        case 30: 
          { System.out.print(" -- "); line=yyline; column=yycolumn; return symbol(sym.DEC);
          }
        case 97: break;
        case 31: 
          { System.out.print(" -= "); line=yyline; column=yycolumn; return symbol(sym.RESTEQ);
          }
        case 98: break;
        case 32: 
          { System.out.print(" *= "); line=yyline; column=yycolumn; return symbol(sym.MULTEQ);
          }
        case 99: break;
        case 33: 
          { System.out.print(yytext()); line=yyline; column=yycolumn; lexeme=yytext(); return symbol(sym.REAL, new Double(yytext()));
          }
        case 100: break;
        case 34: 
          { System.out.print(" == "); line=yyline; column=yycolumn; return symbol(sym.COMP);
          }
        case 101: break;
        case 35: 
          { System.out.print(" %= "); line=yyline; column=yycolumn; return symbol(sym.MODEQ);
          }
        case 102: break;
        case 36: 
          { System.out.print(" != "); line=yyline; column=yycolumn; return symbol(sym.NOTEQ);
          }
        case 103: break;
        case 37: 
          { System.out.print(" && "); line=yyline; column=yycolumn; return symbol(sym.AND);
          }
        case 104: break;
        case 38: 
          { System.out.print(" || "); line=yyline; column=yycolumn; return symbol(sym.OR);
          }
        case 105: break;
        case 39: 
          { System.out.print(" >= "); line=yyline; column=yycolumn; return symbol(sym.MAYOREQ);
          }
        case 106: break;
        case 40: 
          { System.out.print(" <= "); line=yyline; column=yycolumn; return symbol(sym.MENOREQ);
          }
        case 107: break;
        case 41: 
          { System.out.print(" if "); line=yyline; column=yycolumn; return symbol(sym.IF);
          }
        case 108: break;
        case 42: 
          { System.out.print(yytext()); line=yyline; column=yycolumn; return symbol(sym.STR, new String(yytext()));
          }
        case 109: break;
        case 43: 
          { System.out.print(yytext()); line=yyline; column=yycolumn; return symbol(sym.CHAR, new Char(yytext()));
          }
        case 110: break;
        case 44: 
          { System.out.print(" chr "); line=yyline; column=yycolumn; return symbol(sym.CHR);
          }
        case 111: break;
        case 45: 
          { System.out.print(" lon "); line=yyline; column=yycolumn; return symbol(sym.LON);
          }
        case 112: break;
        case 46: 
          { System.out.print(" sup "); line=yyline; column=yycolumn; return symbol(sym.SUP);
          }
        case 113: break;
        case 47: 
          { System.out.print(" syn "); line=yyline; column=yycolumn; return symbol(sym.SYN);
          }
        case 114: break;
        case 48: 
          { System.out.print(" thr "); line=yyline; column=yycolumn; return symbol(sym.THR);
          }
        case 115: break;
        case 49: 
          { System.out.print(" ret "); line=yyline; column=yycolumn; return symbol(sym.RET);
          }
        case 116: break;
        case 50: 
          { System.out.print(" int "); line=yyline; column=yycolumn; return symbol(sym.INT);
          }
        case 117: break;
        case 51: 
          { System.out.print(" nat "); line=yyline; column=yycolumn; return symbol(sym.NAT);
          }
        case 118: break;
        case 52: 
          { System.out.print(" pub "); line=yyline; column=yycolumn; return symbol(sym.PUB);
          }
        case 119: break;
        case 53: 
          { System.out.print(" clas "); line=yyline; column=yycolumn; return symbol(sym.CLASS);
          }
        case 120: break;
        case 54: 
          { System.out.print(" abst "); line=yyline; column=yycolumn; return symbol(sym.ABST);
          }
        case 121: break;
        case 55: 
          { System.out.print(" stat "); line=yyline; column=yycolumn; return symbol(sym.STAT);
          }
        case 122: break;
        case 56: 
          { System.out.print(" true "); line=yyline; column=yycolumn; return symbol(sym.TRUE);
          }
        case 123: break;
        case 57: 
          { System.out.print(" trns "); line=yyline; column=yycolumn; return symbol(sym.TRNS);
          }
        case 124: break;
        case 58: 
          { System.out.print(" this "); line=yyline; column=yycolumn; return symbol(sym.THIS);
          }
        case 125: break;
        case 59: 
          { System.out.print(" else "); line=yyline; column=yycolumn; return symbol(sym.ELSE);
          }
        case 126: break;
        case 60: 
          { System.out.print(" flot "); line=yyline; column=yycolumn; return symbol(sym.FLOT);
          }
        case 127: break;
        case 61: 
          { System.out.print(" fals "); line=yyline; column=yycolumn; return symbol(sym.FALSE);
          }
        case 128: break;
        case 62: 
          { System.out.print(" finl "); line=yyline; column=yycolumn; return symbol(sym.FINL);
          }
        case 129: break;
        case 63: 
          { System.out.print(" null "); line=yyline; column=yycolumn; return symbol(sym.NULL);
          }
        case 130: break;
        case 64: 
          { System.out.print(" priv "); line=yyline; column=yycolumn; return symbol(sym.PRIV);
          }
        case 131: break;
        case 65: 
          { System.out.print(" prot "); line=yyline; column=yycolumn; return symbol(sym.PROT);
          }
        case 132: break;
        case 66: 
          { System.out.print(" bool "); line=yyline; column=yycolumn; return symbol(sym.BOOL);
          }
        case 133: break;
        case 67: 
          { System.out.print(" doub "); line=yyline; column=yycolumn; return symbol(sym.DOUB);
          }
        case 134: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
